/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  admins: string[];
  [k: string]: unknown;
}
export type ExecuteMsg = ExecMsg;
export type ExecMsg = {
  add_member: {
    admin: string;
    [k: string]: unknown;
  };
} | {
  set_beneficiary: {
    address: string;
    [k: string]: unknown;
  };
} | {
  batch_vote: {
    amounts: Uint128[];
    project_ids: number[];
    [k: string]: unknown;
  };
} | {
  end_round: {
    [k: string]: unknown;
  };
};
export type Uint128 = string;
export type QueryMsg = QueryMsg1;
export type QueryMsg1 = {
  admin_list: {
    [k: string]: unknown;
  };
} | {
  round_id: {
    [k: string]: unknown;
  };
} | {
  project: {
    project_id: number;
    round_id: number;
    [k: string]: unknown;
  };
} | {
  project_voter: {
    project_id: number;
    round_id: number;
    voter: string;
    [k: string]: unknown;
  };
};
export interface AdminListResp {
  admins: string[];
  [k: string]: unknown;
}
export interface MapOfUint128 {
  [k: string]: number;
}
export type Uint64 = number;